export const bunny = `                                                                                                           
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms/::--::/+ooooossssyyhhhdhysoooyhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+---:::--..''''..'''.''''....--::--:+yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMh::/osso:..'..''...........-...-:+oso++/+hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMd:/+osyyo..'.........-----..------:oyysooo/oMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMm:::+syyo..--..--.....---::----::::::syysso+/oMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMd::/syyys:-------::----:://////::/+///+yyyyso+:sMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMNo-/oyyyyyo:::--:::////////+++o+++++oo++/syyyyyso/+dMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMh:-/ssyyyyy--:::::/+++ooooooossssssssssss+oyyyyyyso+/oNMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMNo-/oyysyyyyo--://++ssossssssssyyyyyyyyyyso+/yyyyyyysso+/yMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMh::+syyyyyyyy:://+ossyyyyyyyyyyyyyyyyyyyyysso+syyyyyyyyys+/+dMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMNs:+oyyyyyyyyhs-://+syhhhdhysssyyhyysyyhhyyyyso++yyyyyyyyyyo++/sNMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMm+:+syyyyyyyyyy+..-.-:sNMMMNo++ooyyysmNNMNdsssso+/ssyyyyyyyyyss+:+dMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMh:/oyyyyyyyyyyys+---.'../syhs----::://dmmdh+::/++//sssssyyyyyyyso+//hMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMy::oyyysyyyhhyssoo/:---......../yyhhy/::/::-::/+++/+oossssyyyyysysoo++sNMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMs.:oyyyyyyhhyyssooo+/+++///::-:/smNNNmso++++o++ooo++ooooosssssyyyyyysoo+omMMMMMMMMMMMMM    
    MMMMMMMMMMMNs-/syyyyyyyhhyysoooooooossso:--+syyyhhyyyssyyyyysso++ooooooossssssyyyssso+/dMMMMMMMMMMMM    
    MMMMMMMMMMMo:+syyyyyyyhyyssoo++++osso/-....-://++osssssssssooyoooo+ooooosssssyyysssss+/+dMMMMMMMMMMM    
    MMMMMMMMMN+:+syyyyyyyhyysooooooooyy+-.---:::///+++/////:-:-:/+/////+oooooosssyyyysyysooo+hMMMMMMMMMM    
    MMMMMMMMN+-/syyssyyyhhyysoooooosy/..-:::////:+++oooo/-.-------:::---:+ooooossssyyyyysssoo/sMMMMMMMMM    
    MMMMMMMN:-+yhyyyyyyhysssoo+ooosy-.-:///+++oo++sssyy/...-::++/++++/+++/+ooooossssysyyssssso+sMMMMMMMM    
    MMMMMMN/:+syyyyyyhyyssooooo++oy+--/+o+oossyyyyyyyyo.--::/+oooo+++oosoo+osoooosssssyyyyyssssosNMMMMMM    
    MMMMMN+:+syyyyyyhyyssoooooosyyss/++osssyyyyyyyyyso::/+ooossssoooosssso+oooooososssyyyyysyyssooNMMMMM    
    MMMMMo/oyyyyyyhhyysooooooosyyshNyooooosssysssso+///+osyssssyyyyyyyyssoossoooooossssyyyyyyyyysosNMMMM    
    MMMMs:+yhyyyyhhyysoooooosyyysdMMMmsoo:/++oo+/:::/+++syyyyyyyyyyyssssohhsys++oooossssyyyyyyyyysosNMMM    
    MMMd:+syyyyyhhyysooo+ooossoodNMMMMh::--+oss///+++oossssyyyyyyysysssydMMdyssssoooosssyyyyyyyyyysoyMMM    
    MMN+oyhyyyyhhysooo+/:-......-:/+hm/-:://oss/++ooossssssooosso+ommmmmmddddysyssooooosssyyyyyyyyysodMM    
    MMh+shhyyyyhysoo+/-.......''''...--:/+++++//oosyyyyyoooooooso+/y+/:-..''.--:oyysssssoossyyyyyyhyssNM    
    MMooyhyyyyysooo+::://////::-------..:/++o++/+osyyyysoosssssyo:.''...'.....---:osysooooosssyyyyyhyymM    
    MMoyhhyyyysooo+:/ooossssssoo+/::/::::/+oosoooosssssssysysss+.......---:/++oooo++syyssoossssyhyyhhhhM    
    MMsyhyyysoo+oo//ssssyyysysssss++++++/:ossyyyyyyyyyyyyyyyys+....'..-/ossyyyyyyyys+yhyysssssssyyyyhhhM    
    MMhhhysoooosyy/osyyyyyyyyysssyyssoooo/-:syyyyyyyyyyyyhyys:..---.-/oyyyyhyhyyhhyhssdyyhyssooooooshhdM    
    MMNhhysyyyyyyoossyyyyyyyyyssyyyyyssso+//+syyyyyyyyyyyys:-..----/oyyyyyhhhyyhyhhhysdMmdyyhyyssosyhhNM    
    MMMMNmmdddmNN+osyysssyyysyyyyyyyhyyso+ooosyyyyyyyyyyyo//:::////syyhyyhhyhyyhyyhhyyyMMMMNdddhddddmMMM    
    MMMMMMMMMMMMh+osyyyyyyyyyyyyyyyhhyyo+osssssssssssssss+++/://++syyhhhhyhyyyyyyyhhhysMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMyosyyyyyyyyyyyyyyyyhyys+osssssoossssyyssssosoo++osyhhyhhyyhhhhhhhhhhhhymMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMyoyyyyyyyyyyyyyyyyhhyso+ossyhmNNMNNMMMMMMNNhssooosyhhhyyyyhhhhhhhhhhhyydMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMdsyyhhhyhhyhhyyyhhhysooyhdNMMMMMMMMMMMMMMMMMNmdyoosyhhhhyhhhhhhhhhhhhhyhMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMhyhyyhyyyyhhyyhhyysydNMMMMMMMMMMMMMMMMMMMMMMMMMNdyyyhhhyhhhhhhhhhhhhhymMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMdhyyhhyyhhhyhhyyhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdyyhhhyhhhhhhhhhhhyhMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMNdhhhyhyhhhhyhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhhhhhhhhhhhhhhmMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMNmdhhddhhdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhhhhhhhhhhdNMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNddhhhhhdmNMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
                                                                                                            
`;
